# Generated by Django 4.2.1 on 2023-05-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0003_alter_listing_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="listing_location",
            field=models.CharField(default="Viale dei viali", max_length=200),
            preserve_default=False,
        ),
    ]
