# Generated by Django 4.2.1 on 2023-05-28 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0004_listing_listing_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
