# Generated by Django 4.2.1 on 2023-05-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0006_listing_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="listing_image_directory_path"
            ),
        ),
    ]
