# Generated by Django 4.2.1 on 2023-05-30 09:27

from django.db import migrations, models
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0007_alter_listing_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=listings.models.listing_image_directory_path,
            ),
        ),
    ]
