# Generated by Django 4.2.1 on 2023-06-06 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0008_alter_listing_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="square_feet",
            new_name="square_metres",
        ),
    ]
