# Generated by Django 4.2.1 on 2023-06-12 14:09

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0009_rename_square_feet_listing_square_metres"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="category",
            managers=[
                ("custom_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
